name: Build and Test Mini-Database

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Crée les fichiers de build dans le dossier build
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      # Compile le projet
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Test
      # Tente d'exécuter les tests s'ils existent
      # Note: Cela ne fonctionnera que si Test_Student est prêt
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure
